### ISSUE TITLE
Panic at command/sentence.rs:78, range end index 749 out of range for slice of length 493

### ISSUE THREAD

**Issue by edisno** [ferrohd/mikrotik-rs#15]
I get this panic some times, both with newest crates.io version and git head.  Haven't looked into it, just thought i'd leave it here if someone with knowledge of the codebase would know how to fix.

The application panicked (crashed).
Message:  range end index 749 out of range for slice of length 493
Location: [..] mikrotik-rs-6152a6bcc310a1b4/e955906/src/command/sentence.rs:78

**Comment by ferrohd** [comment]
Can you provide more context on this? Specifically what commands was it running?
