### ISSUE TITLE
Increased CPU usage after a call to fetch data from Mikrotik device

### ISSUE THREAD

**Issue by adampwells** [ferrohd/mikrotik-rs#18]
Using this library I can conenct to a Mikrotic router, and fetch a list of leases - so far so good.

After the call completes I see the CPU usage go to 100% for 3 cores (out of 10).

Repeated calls results in all CPUs getting maxed out.

Is this a bug, or am I not 'closing' stuff as appropriate - I followed the example code, and it works, just this crazy usage following the call. I have isolated the call and can confirm that the usage rises after the call is complete and does not drop.

I am using a late version of Rust, Axum and Tokio.

**Comment by adampwells** [comment]
It looks like DeviceConnectionActor is taking up 50% of the thread time... I am using Tokio `join!` to fetch leases from several routers.
 
<img width="852" alt="image" src="https://github.com/user-attachments/assets/a50bc693-3ee5-4ab4-a1b1-8cc431efe35d" />

**Comment by adampwells** [comment]
It looks like the problems occur when the MikrotikDevice instance falls out of scope and is destroyed - there is some kind of panic and the thread just spins.

If I keep a permanent reference to the MikrotikDevice in my application, I can make multiple calls to the device and everything behaves properly.

**Comment by adampwells** [comment]
I can't find a 'proper' way to clean up after creating a MikrotikDevice instance...

**Comment by adampwells** [comment]
It all works as expected now! Many thanks for fixing this issue!

**Comment by ferrohd** [comment]
Thank you for using this library and reporting the issue in detail!
